using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("Astronomy")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("none")]
[assembly: AssemblyProduct("AstronomyPlotter")]
[assembly: AssemblyCopyright("MIT")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("3c9a7a8b-73d4-41eb-9bd7-4bdc2c2b4c7f")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
